### ISSUE TITLE
Ruby error with example glug

### ISSUE THREAD

**Issue by buma** [systemed/glug#3]
I tried example glug in readme and I get an error:
```
/home/mabu/.gem/ruby/2.2.0/gems/glug-0.0.2/bin/glug:5:in `instance_eval': undefined method `[]' for nil:NilClass (NoMethodError)
	from /home/mabu/.gem/ruby/2.2.0/gems/glug-0.0.2/lib/glug.rb:87:in `new'
	from /home/mabu/.gem/ruby/2.2.0/gems/glug-0.0.2/lib/glug.rb:87:in `layer'
	from (eval):5:in `block in <top (required)>'
	from /home/mabu/.gem/ruby/2.2.0/gems/glug-0.0.2/bin/glug:5:in `instance_eval'
	from /home/mabu/.gem/ruby/2.2.0/gems/glug-0.0.2/bin/glug:5:in `block in <top (required)>'
	from /home/mabu/.gem/ruby/2.2.0/gems/glug-0.0.2/lib/glug.rb:71:in `instance_eval'
	from /home/mabu/.gem/ruby/2.2.0/gems/glug-0.0.2/lib/glug.rb:71:in `initialize'
	from /home/mabu/.gem/ruby/2.2.0/gems/glug-0.0.2/bin/glug:5:in `new'
	from /home/mabu/.gem/ruby/2.2.0/gems/glug-0.0.2/bin/glug:5:in `<top (required)>'
	from /home/mabu/.gem/ruby/2.2.0/bin/glug:23:in `load'
	from /home/mabu/.gem/ruby/2.2.0/bin/glug:23:in `<main>'
```

File is converted succesfully if I remove the layer. I'm running ruby `ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]` but don't know enough ruby to debug.

**Comment by nebulon42** [comment]
@buma There seems to be a typo in
`layer(:roads, :zoom=>10..13, :source=>osm_data) {` which
should read
`layer(:roads, :zoom=>10..13, :source=>:osm_data) {`

Then it works for me.

**Comment by buma** [comment]
It seems that there is really a type in example. It works with your change. Thanks.
